### ISSUE TITLE
会話形式のデザインをブログで簡単に書けるようにしたい 🎨👨‍🎨

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#104]
会話形式のデザインは読みやすいので、「自社ブログでも会話形式のデザインを用意するか...!!」という気持ちになっています 😌💭✨

# 会話形式のデザイン例

##  [ハッカーズチャンプルー2019で安川 要平さんに「中途未経験からwebエンジニア転職を目指す際の戦略」でアドバイスを頂いたお話 | プログラミング学習日記](https://tukinasikotonoha.net/yasukawa-yohei)

[![60397273-0c8cfc80-9b86-11e9-804c-62fc8367e341](https://user-images.githubusercontent.com/155807/60397339-077c7d00-9b87-11e9-8299-d77a528d42ce.png)](https://tukinasikotonoha.net/yasukawa-yohei)

<br>

##  [「たとえ報酬がゼロでも、複業をやっていた」──西尾泰和がサイボウズ・ラボを辞めずに、機械学習の技術顧問を始めた理由](https://cybozushiki.cybozu.co.jp/articles/m001358.html)

[![60397320-d2702a80-9b86-11e9-9974-8007f2e2b039](https://user-images.githubusercontent.com/155807/60397342-119e7b80-9b87-11e9-9889-f688389fa257.png)](https://cybozushiki.cybozu.co.jp/articles/m001358.html)

**Comment by hanachin** [comment]
向かい合って話しているように見える写真が必要そう

**Comment by yasulab** [comment]
> 向かい合って話しているように見える写真が必要そう

あったら better かなとは思うけど、吹き出しのデザインがあれば十分伝わるので、向かい合って話しているように見える写真が「必要」とは思わないかなぁ 👀 💭 

## 向かい合ってない写真の例

![image](https://user-images.githubusercontent.com/155807/60405921-0f233c80-9bee-11e9-920c-f153d8bcc24d.png)

**Comment by hanachin** [comment]
これは個人の感じ方だと思いますが、サイボウズの方は対談に見えますが、ことのはさんのブログの方は会話してるようには見えますが対談には見えなかったので。

> ［名］(スル)向かい合って話し合うこと。また、ある事柄について二人で話し合うこと。対話。
https://kotobank.jp/word/%E5%AF%BE%E8%AB%87-557756

**Comment by yasulab** [comment]
なるほど「会話 != 対談」という認識なのね。Issue のタイトルの方を変えました 😉

**Comment by yasulab** [comment]
こちら現在は note に移行したので Close しますね! https://yasslab.jp/ja/news
