### ISSUE TITLE
Algolia の検索エンジンを追加してサイト内検索を簡単にしたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#105]
https://yasslab.jp/ 内のコンテンツが増えてきたので、Algolia を使ってサイト内検索を簡単にできる仕組みを導入してみても良さそう🤔💭

### ブログ記事
https://yasslab.jp/ja/posts
![image](https://user-images.githubusercontent.com/155807/60408208-ef454600-9bf8-11e9-97df-5dd145cac861.png)

### 事業実績
https://yasslab.jp/ja/works
![image](https://user-images.githubusercontent.com/155807/60408231-008e5280-9bf9-11e9-9510-3e4ad7ca036b.png)

### 開発支援
https://yasslab.jp/ja/agile
![image](https://user-images.githubusercontent.com/155807/60408248-13088c00-9bf9-11e9-8b1f-4061bee7ad83.png)

### 採用情報
https://yasslab.jp/ja/join-forces
![image](https://user-images.githubusercontent.com/155807/60408313-5ebb3580-9bf9-11e9-8943-c8ec755ce7b2.png)

### 公開資料 (の１つ「就業規則」)
https://yasslab.jp/ja/docs/work-regulations
![image](https://user-images.githubusercontent.com/155807/60408347-801c2180-9bf9-11e9-8d5b-8a483091d21b.png)

**Comment by Yuppymam** [comment]
🔽参考になりそうでした💻✨
[algoliaを使ってJekyll製ブログに全文検索をつけた話](https://aloerina01.github.io/blog/2018-10-11-1)

**Comment by yasulab** [comment]
こちら Jekyll 用の Search Plugin (JavaScript) で解決したので Close します! 🙏 ✨ 
https://github.com/christian-fei/Simple-Jekyll-Search

<img width="845" alt="image" src="https://github.com/yasslab/yasslab.jp/assets/155807/fad34eb6-dee3-4df2-8fc1-0e381839486f">
