### ISSUE TITLE
ロゴの検討

### ISSUE THREAD

**Issue by showw** [yasslab/yasslab.jp#12]
- Yのみバージョン
- YとLの一体型

どちらが良いか、ご検討いただけますか？
トップページに入れてみた状態のキャプチャを２種類、添付します。

<img width="1094" alt="2018-05-21 9 20 11" src="https://user-images.githubusercontent.com/5765654/40285628-8f464916-5cd9-11e8-94a1-8f91dfcd2021.png">
<img width="1091" alt="2018-05-21 9 26 09" src="https://user-images.githubusercontent.com/5765654/40285629-8f76fa02-5cd9-11e8-840a-c71ac8612328.png">

**Comment by yasulab** [comment]
> Yのみバージョン

こっちの方がシンプルで良いと僕は思いました!  💖 比較画像ありがとうございます 😸

**Comment by showw** [comment]
お返事ありがとうございます！それではYのみバージョンで進めますね

**Comment by yasulab** [comment]
はい! 引き続きよろしくお願いします 😆
