### ISSUE TITLE
「秘密情報を仕組みで守る」の図を修正する

### ISSUE THREAD

**Issue by showw** [yasslab/yasslab.jp#129]
- [ ] 「フルタイム勤務者」ではなく「雇用契約社員」に変更する
- [ ] 「複業勤務者」から「複業契約社員」に変更する

https://yasslab.jp/ja/join-forces
![image](https://user-images.githubusercontent.com/5765654/62510739-44552700-b84b-11e9-8aff-9bfc3f83afb1.png)

**Comment by yasulab** [comment]
ありが鯛 🐟✨
