### ISSUE TITLE
お知らせページだけヘッダーのフォントが違う? 👀

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#146]
微妙に違うっぽい 👀 💭 

![image](https://user-images.githubusercontent.com/155807/64225474-9060bd80-cf16-11e9-93b8-24290d382aba.png)

- https://yasslab.jp/ja/agile
- https://yasslab.jp/ja/news

**Comment by yuki384** [comment]
https://github.com/yasslab/yasslab.jp/pull/261 でfixしたので閉じます〜
