### ISSUE TITLE
トップページのメイン画像：スマホサイズ用を作る

### ISSUE THREAD

**Issue by showw** [yasslab/yasslab.jp#22]
現在のトップ画像が、スマホの時に大きすぎるため、スマホ用サイズを作って、smallとlargeを出し分けする。

**Comment by yasulab** [comment]
🙏 💦

**Comment by yasulab** [comment]
😻💓

**Comment by showw** [comment]
ブランチresponsive-imgで出し分けをしてみました。
ご確認ください。
@yasulab

**Comment by yasulab** [comment]
👀

**Comment by yasulab** [comment]
.oO(Pull Request にして欲しいです...!!)

**Comment by yasulab** [comment]
PRありがとうございます! 🙏 ✨ https://github.com/yasslab/yasslab.jp/pull/23
