### ISSUE TITLE
研修プランを重視したトップページのリニューアル

### ISSUE THREAD

**Issue by showw** [yasslab/yasslab.jp#239]
まずは内容の整理とアイデア出し

# 創って学ぶ、学んで創る

## 個別カスタマイズあり

学びを支える技術(B to B)
1. 研修プラン
	- 御社のビジネスをブースト
		- 新入社員研修
			- マネーフォワード
	- リクルートにも有用（スキルアップできますよ）
		- 通常業務中の研修
			- メンキャリ
		- 海外から日本に就職する人のリクルートとトレーニング
		- オフショアではなく、日本国内採用
2. パートナープラン 法人ごとに値段を変更できる
	- 新しいビジネスをはじめませんか
3. 開発支援

---
## 個別カスタマイズしない（システムが整っている）

4. 法人プラン
5. チームプラン

**Comment by showw** [comment]
## グローバルナビの見直し。

###  現状
- 学びを支える技術
- 月額制の開発支援
- お知らせ
- 会社情報
    - YassLab 社のやること
    - これまでの事業実績
    - コミュニティ活動
    - プレスリリース
    - 採用情報 (複業採用含む)
    - 公開資料 (就業規則など)
- お問い合わせ
- English

###  修正案
お問い合わせとEnglishはフッターにあるため、上部グロナビからは削除する。
＊印が新しくグロナビに追加するメニュー。

- 学びを支える技術
- 研修プラン＊
- パートナープラン ＊
- 月額制の開発支援
- お知らせ
- 会社情報
    - YassLab 社のやること
    - これまでの事業実績
    - コミュニティ活動
    - プレスリリース
    - 採用情報 (複業採用含む)
    - 公開資料 (就業規則など)

## トップページ修正案
まずは、研修プランをもっと前面に出すために `railstutorial.jp/training` への導線をつくる。
導入企業一覧のロゴもトップページに配置する。
![top-page2020](https://user-images.githubusercontent.com/5765654/72216365-3b3b5500-3563-11ea-85d5-d0f5a576ab59.jpg)

@yasulab @megane9988  ご意見お待ちしてます。

**Comment by yasulab** [comment]
> * 研修プラン＊（ページ内リンク or 新規ページ作成？ or [https://railstutorial.jp/trainingにリンク）](https://railstutorial.jp/training%E3%81%AB%E3%83%AA%E3%83%B3%E3%82%AF%EF%BC%89)
> * 協業プラン ＊（https://railstutorial.jp/partner にリンク）

こちらページないリンクでお願いしたいです (＞人＜ )✨

**Comment by yasulab** [comment]
> トップページ修正案

@showw 良さそうです！！😻🆒✨ まずは手元の素材で可能な範囲で対応していき、改善は後日別途していけると嬉しいなと考えています！ :blush: 💖
