### ISSUE TITLE
トップページの画像をCSSではなくレスポンシブイメージで表示する

### ISSUE THREAD

**Issue by showw** [yasslab/yasslab.jp#24]
今はCSSのメディアクエリで、大きい画像と小さい画像を両方読み込んで、ブラウザの幅に合わせて、どちらかを表示する、という形式になっている。
これを、picture要素を使ったレスポンシブイメージに変更する。
picture要素を使ってページを読み込むと、画像がPCかスマホのどちらか片方しか読み込まなくなるため、表示速度は速くなるはず。
https://www.doe.co.jp/hp-tips/html5/picture-element/

**Comment by showw** [comment]
top-pictureブランチを作ってやってみましたが、ロゴとキャッチコピーの配置がうまくいかなくて、いったん保留。Backlogにはpushしてあります。

**Comment by megane9988** [comment]
#30　にて対応済です。
