### ISSUE TITLE
問い合わせフォームのメールアドレスをmailtoにする

### ISSUE THREAD

**Issue by showw** [yasslab/yasslab.jp#26]
「メールによるお問い合わせは yohei@yasslab.jp まで。」
のメールアドレスをmailtoにしておき、クリックしたらメーラーが立ち上がるようにする。

**Comment by yasulab** [comment]
Gmail ユーザーの場合は `mailto` がリンクになっているのと Mailer が立ち上がってしまって閉じる必要が出て来てしまうので、「mailto の方が良い」という根拠が出揃うまではとりあえず使わないようできればなと思います 🙏 💦 

一旦閉じちゃいますね ;)
