### ISSUE TITLE
キャッチコピーの変更

### ISSUE THREAD

**Issue by showw** [yasslab/yasslab.jp#268]
ロゴ下のキャッチコピーを以下のものに差し替える。

Having a Good Life by Creating ;)

**Comment by yasulab** [comment]
Issue 作成ありがとうございます！(＞人＜ )✨

**Comment by showw** [comment]
@yasulab 
ロゴのキャッチコピー変更、illustratorのデータを修正しました。
共有しているDropBoxの「YassLab株式会社_公開ロゴデータ」の中に入れてありますが、これでよろしいでしょうか？

**Comment by yasulab** [comment]
@showw ありがとうございます！拝見しますね :eyes: 💨 ✨

**Comment by yasulab** [comment]
@showw ロゴ画像、キャッチコピー以外の部分も変わっていますが (ロゴが縦に長くなったりロゴの位置が右に少しずれていたり)、こちらは意図した仕様変更ですか? 🤔💭

## before
![image](https://user-images.githubusercontent.com/155807/74694813-f2974b80-5234-11ea-81cd-42bb903bcff5.png)
![image](https://user-images.githubusercontent.com/155807/74694849-1e1a3600-5235-11ea-89f8-2120a109ae6d.png)


## after
![image](https://user-images.githubusercontent.com/155807/74694823-00e56780-5235-11ea-87bd-6d34d45b11bf.png)
![image](https://user-images.githubusercontent.com/155807/74694855-25d9da80-5235-11ea-81f6-af6e761a61f0.png)

**Comment by yasulab** [comment]
あー、青と白の正方形ロゴでロゴ位置がズレてるのは、変更履歴を見えるとこれは元からズレてたっぽい気がしますね 👀💭

**Comment by showw** [comment]
## 2/18ミーティング修正箇所

- 正方形の中心線
- 青色版のsvgとpdfも角丸にしたい
- 背景透明版のsvgとpngは、角丸関係なし

**Comment by showw** [comment]
DropBoxの以下のファイルを背景角丸にしました。
- yasslab-text.svg
- yasslab-text.png

![image](https://user-images.githubusercontent.com/5765654/75626795-e389a380-5c0d-11ea-820b-39c09431a724.png)

### 正方形の白背景ロゴの中心線について

Afterの方を採用させてください。
ロゴマークが左右非対称ではない形のため、元々少しズラした位置にしておりました。位置のズレは非常に微妙なのですが、今回もう少し中心寄り（それでも真ん中ではない）にしているのがAfterの状態です。
詳しくはzoomミーティングの時に見せながら、ご説明しますね。

**Comment by showw** [comment]
@yasulab 
キャッチコピーの変更としてはいったんこのissueはcloseさせていただき、別issueとしてロゴの整理をさせていただきたいのですが、よろしいでしょうか？
YassLab株式会社_公開ロゴデータを見直していたのですが、細かいところで修正を加えるべきところがありました、、、

たとえば、ご指摘のあった青背景と白背景でマークの位置が微妙に違ったりもそうですが、

円の部分で、完全にパスを削除するべきところでパスが残っているために、微妙にラインが出てしまっていたり
![image](https://user-images.githubusercontent.com/5765654/75855850-7efd5d00-5e36-11ea-94fd-11137acd3f3a.png)

青背景のものは全部角丸に統一するべき、など。

いったん「YassLab株式会社_公開ロゴデータ」を私の方でダウンロードして、全ファイル確認して調整を加えてからお渡しする、ということをしたいと考えております。

**Comment by showw** [comment]
上記に関しては、別課題をたてました。
https://github.com/yasslab/yasslab.jp/issues/277

この課題は対応済みなのでクローズします。
