### ISSUE TITLE
ロゴの整理

### ISSUE THREAD

**Issue by showw** [yasslab/yasslab.jp#277]
![logo](https://user-images.githubusercontent.com/5765654/76184678-1cc6a280-6210-11ea-82d5-dc6c47c7901d.png)
円の部分で、完全にパスを削除するべきところでパスが残っているために、微妙にラインが出ている。

**Comment by showw** [comment]
YassLabサイトの「ブランドガイドライン」からダウンロードして、ロゴデータを整理しました。
主な変更点は以下の通りです。

- 余計なパスが残っていたのを削除
- 青背景で角丸になっていなかったものを角丸に
- センターがズレているものがあったのを調整
- 白背背景のもので、角丸背景がないのにファイル名が「yasslab-rect.svg」となっていたので、「yasslab-white.svg」に名称を変更

Dropboxの共有フォルダ「mgn×YassLab」の中の以下のフォルダに置きましたので、現状の公開データと差し替えていただけますか。

YassLab > YassLab株式会社_公開ロゴデータ-0314

@yasulab

**Comment by yasulab** [comment]
@showw ロゴ画像の更新ありがとうございました！先ほど内容を確認して、公開ロゴデータからリリースしました！😆🎉✨ https://yasslab.jp/ja/brand

こちらの Issue についても完了したと思うので、一旦閉じちゃいますね 😉
