### ISSUE TITLE
お知らせページの記事がいつのものなのかわかりにくい

### ISSUE THREAD

**Issue by yuki384** [yasslab/yasslab.jp#318]
https://yasslab.jp/ja/news/ に、年度表記をいれる

参考: https://yasslab.jp/ja/works

2018年〜2019年の記事の表示
![image](https://user-images.githubusercontent.com/31533303/82022199-36c8a980-96c7-11ea-8866-e8c2abc4902d.png)

2020年の記事の表示
![image](https://user-images.githubusercontent.com/31533303/82022222-40eaa800-96c7-11ea-9d2f-530944681be0.png)

↑わかりにくい…

年度を示す見出しを入れる

**Comment by yasulab** [comment]
とりあえず年表示だけ実装しました！細かなコードのリファクタリングはあとでやります！🛠💨✨

> [yasulab](/yasulab) closed this in ` [769578f](/yasslab/yasslab.jp/commit/769578f851518a794d305642b7e3e2835c4beaf8) ` [now](#event-3343410488)

**Comment by yasulab** [comment]
![image](https://user-images.githubusercontent.com/155807/82116419-9ba60180-97a4-11ea-8718-38488553ebe4.png)
