### ISSUE TITLE
/dist ディレクトリを CI から生成するようにする

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#33]
並行して作業すると生成物の conflict が発生してマージに手間がかかるので直したいです >< 💦 

cf. コンフリクトの例: https://github.com/yasslab/yasslab.jp/pull/29

**Comment by naopontan** [comment]
@yasulab

すみません、教えてください 🙏
/dist フォルダは何らかのコマンドで生成するのでしょうか?

jekyll まわりを調べてみたのですが、よくわからず...😥💦

あと、 CI まわりの情報源等も教えて頂ければ助かります 🙇🏻

**Comment by yasulab** [comment]
README を読んでいただければ! 😸 
https://github.com/yasslab/yasslab.jp

**Comment by yasulab** [comment]
> CI まわりの情報源等も教えて頂ければ助かります 🙇🏻

CI はこちらを読んでもらえれば! 😸 
https://github.com/yasslab/yasslab.jp/blob/master/.travis.yml

Idobata に流れている CI 結果からも辿れると思います 📑 👀

**Comment by naopontan** [comment]
[WIP]
もしかして、 `.gitignore` に `dist/css` を追加するだけで対応できるかも..🤔

- [ ] .gitignore に dist/css を追加し、 git の管理対象から外す
  - dist/img は人が管理(コマンドで生成ではない)ので git 管理対象のまま
- [ ] デプロイ時は `npm run css` が走るように調査する(既に走るようになっているかも)
- [ ] ローカル開発環境時に影響が出ないか確認する

引き続き作業進めます 🔧💨

**Comment by naopontan** [comment]
対応しました。これで大丈夫だと思います。
ブランチにプッシュしても CI はチェックしてくれるんですね✨
今から PR 出します。

**Comment by yasulab** [comment]
お待ちしております! 👍 ✨

**Comment by yasulab** [comment]
@naopontan いったん Issue を re-open しておきますね ;)
cf. https://github.com/yasslab/yasslab.jp/pull/37#issuecomment-399297877
