### ISSUE TITLE
スマホ版のフッター項目の左端と右端を揃える

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#336]
...と、揃ってる感が出るかも...? 🤔💭 (とはいえ優先度は低め :relieved: :sparkles: ) cc/ @yuki384 

![image](https://user-images.githubusercontent.com/155807/84988515-19cb3e80-b17d-11ea-9d65-99f42b866d11.png)

**Comment by yuki384** [comment]
揃えるとこうなります…💦
![image](https://user-images.githubusercontent.com/31533303/90598726-8e2e6680-e22e-11ea-8b2e-551290cba018.png)

**Comment by yasulab** [comment]
あー、どっちも微妙ですね 🤣 もし着手するなら、別の見せ方にした方が良さそう！🎨✨

**Comment by yasulab** [comment]
こちら Close しますね！検証スクショありがとうございました！(＞人＜ )✨
