### ISSUE TITLE
お問い合わせフォーム『内容』フォームの padding を調整する

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#390]
お問い合わせフォームの内容フォームだけ padding がずれているようなので調整したい 👀💨✨ (内容フォむのみ Focus Bar が表示されないため)

![image](https://user-images.githubusercontent.com/155807/97107968-bc886080-170d-11eb-8489-71c8d6fe784a.png)

cf. https://github.com/coderdojo-japan/coderdojo.jp/commit/cf6347da9d4a4be5e3ea52853ca581fa6d76d4db
cf. https://github.com/coderdojo-japan/coderdojo.jp/issues/887

**Comment by yasulab** [comment]
こちら無事修正できました！🛠💨✨

![image](https://user-images.githubusercontent.com/155807/97125731-2fc6bc80-1778-11eb-8879-ead676b01e41.png)

**Comment by showw** [comment]
このファイルは削除完了しました。
![image](https://user-images.githubusercontent.com/5765654/97129663-d1eba200-1782-11eb-8cb6-22e5a53ac167.png)
![image](https://user-images.githubusercontent.com/5765654/97129655-cc8e5780-1782-11eb-8c43-884ae0754c7a.png)
