### ISSUE TITLE
Qiita と GitHub の統計情報取得スクリプトを実装したい

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#4]
会社のウェブサイトのリニューアル向けて現在 @yasslab/mgn チームと一緒に準備を進めています。リニューアル後のWebサイトには Qiita と GitHub の統計情報を表示する部分があるのですが、そこの設計と実装面を @aokabin さんと @AnaTofuZ さんにお願いしたいです...!! 🙏 

背景: 📜 Webサイトをリニューアルする
https://yasslab.qiita.com/projects/16852

## 統計情報とやりたいこと
リニューアル後のTopページでは、次の画面を表示したいと考えています。デザインなどは mgn チームにお願いしていますが、画面下部にある Qiita と GitHub の統計情報を取得する部分の設計と実装を考えていただけないかなと考えています🤔

![qiita-and-github](https://user-images.githubusercontent.com/155807/38917425-bc016468-4325-11e8-80f9-43e21caf5061.png)

### やりたいこと

1. Qiita Organization 所属メンバーの合計投稿数と合計いいね数を表示させたい
   - YassLab Organization: https://qiita.com/organizations/yasslab
   - API を見てみないとわからないですが、もしピンポイントで欲しい情報が取得できれば簡単かも...?
2. GitHub Organization にある合計リポジトリ数 (Public のみ) と合計スター数 (Public のみ) を表示させたい
   - YassLab Organization: https://github.com/yasslab
   - こちらも API を見てみないとわからないですが、集計処理を書く必要があるかもしれないです ><

## お願いしたいこととアプローチ案

上記の２つの統計情報を取得したいと考えていますが、いくつかのアプローチがありそうです🤔 それぞれのアプローチを比較検討または提案してもらって、最も良さそうだと思うアプローチを判断し、その実装をしてもらいたいです 🙏 

@yasulab が現時点で思いついているアプローチは次の通りです。他にも良い方法があるかもしれませんが、取っ掛かりとしてご参考にしてもらえれば 😸 

1. JavaScript で実装して、描画するタイミングで計算・表示する
   - 提供されている API にもよりますが、もし複雑な計算が必要なければこれが早いかもしれません
2. Ruby などで定期的に cron で統計情報を取得し、そのデータを表示する
   - Heroku Scheduler + cron スクリプトで定期的にデータを取得し、そのデータを描画する方法です
   - 欲しい情報を算出するのに複雑な計算が必要だったり、`1.` のレスポンスタイムが長かった場合はこちらの方が有効かもしれません。
   - Jekyll は静的サイト用に作られたツールなので、もし Ruby で統計情報を処理する場合は Jekyll Plugin を書く必要がありそう🤔 Plugin レベルでは Ruby スクリプトを比較的自由に書けます 💎📝 https://jekyllrb-ja.github.io/docs/plugins/

## アクション
まず API 周りの調査から始めると良さそうです。以下、大雑把に必要そうなタスクを書き出していますが、最初の一歩として参考にしてもらえれば幸いです ;)

- [ ] [dev branch](https://github.com/yasslab/yasslab.jp/tree/dev) を fetch して環境構築をする
- [ ] Qiita API を調べる
- [ ] GitHub API を調べる
- [ ] `1.` のアプローチが良いか、`2.` のアプローチが良いか、あるいはそれ以外の良いアプローチがあるか検討する
- [ ] 最も良いと思われるアプローチを実装する
- [ ] 実装したスクリプトのテストコードを書く
- [ ] 統計情報の取得方法を mgn チームと共有し、mgn チームで描画できれば完了

**Comment by AnaTofuZ** [comment]
一旦まずcloneして環境構築を行ってみます

**Comment by AnaTofuZ** [comment]
`bundle install --without production --path vendor/bundle` を実行しました。
READMEに書かれている通りに 
- `npm install`
- `npm run css` 
- `npm run watch` をバックグランドで実行
- `be jekyll server` で確認しました

**Comment by yasulab** [comment]
🆒 ✨

**Comment by AnaTofuZ** [comment]
READMEにもありましたがjekyll serverで確認できるのは現在のyasslab.jpのwebサイトの様です。
その為、デザイン的な実装は置いておいて進めていきます

**Comment by yasulab** [comment]
@AnaTofuZ あー、 `demotop.html` を開くとそれっぽいページが見れるかも? どうでしょう?

@megane9988 先ほど CASE で見せていただいたファイルって今 `dev` ブランチにありますか? もしなければ push してもらえると嬉しいです! 😸

**Comment by AnaTofuZ** [comment]
@yasslab/core-team `open demotop.html` を実行した所確認できました! ありがとうございます!!

**Comment by yasulab** [comment]
お、fetch するといい感じのファイルになりそう🤔💭

<div>
<span><img src="https://avatars3.githubusercontent.com/u/1205958?v=4" width="16" height="16" alt="" /></span>
<a href='https://github.com/megane9988'>megane9988</a>
pushed to
<a href='https://github.com/yasslab/yasslab.jp/tree/dev'>dev</a>
at
<a href='https://github.com/yasslab/yasslab.jp'>yasslab/yasslab.jp</a>
(<a href='https://github.com/yasslab/yasslab.jp/compare/32f558a9540b...3aba3e204296'>compare</a>)
</div>
<ul>
<li>
<a href='https://github.com/yasslab/yasslab.jp/commit/2ba180a04a4ad776edd2fc701c86c502c1352801'><tt>2ba180a</tt></a>
共有のためひとまずpush

</li>
<li>
<a href='https://github.com/yasslab/yasslab.jp/commit/3aba3e204296c9419343b0d4b316fc63c06f6f01'><tt>3aba3e2</tt></a>
Merge branch &#39;dev&#39; of github.com:yasslab/yasslab.jp into dev

</li>
</ul>

**Comment by AnaTofuZ** [comment]
pullして更新しました．
まずはQiitaのAPIについて調べてみます．Javascriptの実装の場合はfetchを使ったりする感じかな・・・

**Comment by yasulab** [comment]
１点補足ですが、Jekyll は静的サイト用に作られたツールなので、もし Ruby で統計情報を処理する場合は Jekyll Plugin を書く必要がありそうですね🤔 Plugin レベルでは Ruby スクリプトを比較的自由に書けるので 💎📝 
https://jekyllrb-ja.github.io/docs/plugins/

**Comment by AnaTofuZ** [comment]
なるほどJekyllPluginですね! ありがとうございます:pray: 

QiitaのAPIですが,QiitaTeam関連のAPIを利用する場合は認証が必須のよう(書き方から必要でないとも取れるので試してみます)
cf.https://qiita.com/api/v2/docs#%E8%AA%8D%E8%A8%BC%E8%AA%8D%E5%8F%AF

また「いいね」を取得するAPIは非推奨となり，絵文字から`+1` の数を取得する方式のようです
cf.https://qiita.com/api/v2/docs#%E7%B5%B5%E6%96%87%E5%AD%97%E3%83%AA%E3%82%A2%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3

またこのAPIは投稿に個別に紐付いているので，QiitaTeamのuserの投稿一覧を取得,それぞれのいいねを入手,合算という処理になりそうです．処理の内容が多そうなのでJekyllにやらせるのが良いかなと思ってきました

**Comment by yasulab** [comment]
良さそう! 😸 まずは色々と書き捨てのスクリプトを書いて試して見るのが良いと思います 👍 ✨

**Comment by AnaTofuZ** [comment]
なるほどです!! 軽いスクリプト書いて試してみます．
cronでデータを保存する時はおそらくDBに保存する事になると思うので，そのあたりも考えています

**Comment by AnaTofuZ** [comment]
試しにAPIを叩くスクリプトを作成しています．
RubyでURIのquery parameterを作成するのはActive Supportを使うと楽…?

**Comment by AnaTofuZ** [comment]
調べていた所Qiitaには[qiita-rb](https://github.com/increments/qiita-rb)というgemがあったので，これを上手く活用していくと良さそうということが解ってきました

**Comment by aokabin** [comment]
今入りました、並列して僕の方では [GitHub API](https://developer.github.com/v3/)を調査しますー

**Comment by yasulab** [comment]
Qiita/GitHub、いずれも本番環境で動いていることが確認できたので完了としますね 😸✅ 
実装お疲れ様でした〜〜〜 😊✨ 
https://yasslab.jp/ja

<img width="322" alt="screen shot 2018-05-31 at 2 50 58" src="https://user-images.githubusercontent.com/155807/40753804-ec422d90-64b0-11e8-9383-dde435f5a761.png">
