### ISSUE TITLE
PR時に生成される Heroku Pipeline の RACK_ENV を修正しないで済むようにしたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#40]
@AnaTofuZ こういうことってできますかね? 🤔💭 毎回 Heroku Dashboard にいって RACK_ENV を `production` から別の文字列に変更するのが面倒なので >< 💦

**Comment by yasulab** [comment]
ありがとうございます! よろしくお願いします 😸

**Comment by AnaTofuZ** [comment]
以前RailsTutorialでも同じ作業をしたのですが，肝心の設定場所が何故か見当たらなくて探しています

**Comment by AnaTofuZ** [comment]
`app.json`の設定フォームがやはり見つからない…!?

**Comment by yasulab** [comment]
こちら対応されていると思うので、Close しますね！（いつ対応したか忘れてしまった... 😹)

**Comment by yasulab** [comment]
これかな！ :eyes: ✅ https://github.com/yasslab/yasslab.jp/commit/1252ef75959bc12397bbe77082936f86f45c6589#diff-6a1b6963e828b69fcc667e3c45df78bb
