### ISSUE TITLE
幅2048pxサイズでトップの画像に見切れが生じる

### ISSUE THREAD

**Issue by aokabin** [yasslab/yasslab.jp#47]
## 問題について

HPを2048px幅で閲覧すると、トップページの画像の右側が見切れてしまう。

[YassLab 株式会社 – Having a Good Life with OpenSource ;\)](https://yasslab.jp/ja/)

![2018-07-06 15 12 45](https://user-images.githubusercontent.com/3102940/42362744-a720519c-812f-11e8-9e35-dc070b0b97e4.png)

**Comment by yasulab** [comment]
@megane9988 @showw 🙏 ✨

**Comment by yasulab** [comment]
Fixed by https://github.com/yasslab/yasslab.jp/pull/48 ✅ ✨
