### ISSUE TITLE
GitHub API関連の調査

### ISSUE THREAD

**Issue by aokabin** [yasslab/yasslab.jp#5]
### 関連issue

#4 

この中のGitHub APIの調査部分に関するまとめはこのissue内でやっていく

**Comment by aokabin** [comment]
# issue作るまでのメモ

## 先にHPのclone

https://github.com/yasslab/yasslab.jp
clone中...

ローカルで動かして見たいな、jekillらしい

bundle install
bundle exec jekyll serve

動いて動作確認した

## GitHub APIについての調査
基本ここに色々ある
https://developer.github.com/v3/
rubyで扱う場合
https://github.com/octokit/octokit.rb
参考[octokit.rbの使い方まとめ](https://qiita.com/kompiro/items/0504c70eb8f522e1f66a)

organizationの統計情報を取るにはどうしたらいいのか？というのを調べたい

どの数値を取るのか、も気になるところではある

どういう値が取れるのか？も知る必要がありそう

## ゴール

GitHubAPIを使って、organizationの統計情報(publicRepo数と合計スター数)を表示したい

## 調べること

- GitHubAPIではどういう情報が取得できそうか
- Jekyll環境でRubyを動かすべきか、JSで取得するべきか
- Heroku Scheduler + cronを使う場合、データはどこに保存する？
  - DB？yaml？すでにデータを保存するのに似たやつがある？


### 思考の整理

GitHubAPIを調べて、どういうデータが取得できるのか、は単独でできそう
Jekkyll環境で何を使うかは、DBの状態が関係して来そうな気もする

## GitHub APIについて

GitHub APIでどうやったら合計Public Repo数を取得できる？
同じくスター数も取得できる？

https://developer.github.com/v3/

まず、Organizationsでは、リポジトリ数やスター数も厳しい
RepositoryのStatisticsは？

starでは出てこなかった
https://developer.github.com/v3/repos/#list-organization-repositories
この中のレスポンスに`"stargazers_count"`ってのがあって、これがスター数だと思われる。

これ使ったら余裕なのでは

**Comment by aokabin** [comment]
なお、APIはキーなしで叩ける様子
curl --silent 'https://api.github.com/repos/yasslab/railsguides.jp' -H 'Accept: application/vnd.github.preview' | jq '.watchers_count'

**Comment by aokabin** [comment]
curl --silent 'https://api.github.com/orgs/yasslab/repos' -H 'Accept: application/vnd.github.preview' | jq -C '.[].stargazers_count' | less -N

これが結構いい感じに取れている感じする

**Comment by aokabin** [comment]
`curl --silent 'https://api.github.com/orgs/yasslab/repos' -H 'Accept: application/vnd.github.preview' | jq -C '.[].stargazers_count' | wc -l`
でリポジトリ数

`curl --silent 'https://api.github.com/orgs/yasslab/repos' -H 'Accept: application/vnd.github.preview' | jq -C '[.[].stargazers_count] | add'`
でスター数の合計値が取れる

**Comment by aokabin** [comment]
んー、動作を見ている感じ、集計処理は自分でやらないと行けなさそうだけど、jsで書いてもそこまで遅くはならないんじゃないかなーという気がする

**Comment by aokabin** [comment]
一旦ストップ、どうやってjsファイルを読み込ませるかを考えて行きましょう

**Comment by yasulab** [comment]
思考過程がすごくよくまとまっていて素敵ですね...!! 😊✨ 
調査結果から「まずは js で試していこう」という過程にもとても納得感がありますね 👍 💖

**Comment by aokabin** [comment]
嬉しいです... 🙏 ありがとうございます！ 😄 
精進していきます 💪

**Comment by aokabin** [comment]
jekyllにてどうやればjsが読めるだろうか
とはいえheaderに書き込めば読めそうなので、書いてみる
もし他にいい案があったらレビューしてくれるはず...！という浅はかさで作り始めていこうかな

**Comment by aokabin** [comment]
footer.htmlに
`<script type='text/javascript' src='/js/main.js'></script>`
こんな感じで書いてみた
ちゃんとロードしてくれたっぽい

ここでそのままmain.jsに書くよりは、main.jsからstatistics_github.jsファイルくらいを読み込むのがいいんじゃないかなーと思ったので、その方針で進めることを考える
一応アナグラくんの進め方も見ながら考えてみる

**Comment by aokabin** [comment]
アナグラくんの方はrubyでやる感じだったので、方針が違いそう
お互い同じファイルを触る感じはしなかったので、こちらは前述の方針で進めても良さそう

**Comment by aokabin** [comment]
もしかしてネイティブのjsって他のファイルを読み込む機能ない...？
というか別に分けたまま書いてscriptタグでロードすればいいから別に気にしなくていいか

ES6とかの記法で書いてもいいのだろうか...？

**Comment by aokabin** [comment]
@yasulab 実際どんな感じでコードを書くかはそこまでイメージできていないのですが、ES6とかは使わない方がいいでしょうか？(IEからのアクセスとかも考えられますよね？)

**Comment by aokabin** [comment]
最終的なアウトプットをどうするのがいいんだろう...？
とりあえずオブジェクトを返す関数を作っておいて
そいつのパラメータを操作するようにしようかな

**Comment by aokabin** [comment]
ieがある可能性があるならPromiseとかは使えなさそう...
仕方ないから一旦callback地獄的実装にしようかな...

**Comment by aokabin** [comment]
callbackをちゃんと理解していないんだなぁとしみじみ...
dom操作をするための関数をcallbackで渡してあげればOKかな

**Comment by yasulab** [comment]
> IE からのアクセスとか

今回目的としているターゲット層ではないので、今はまだ使わないで貰えると助かります (＞人＜;)
https://yasslab.qiita.com/projects/16852

今後なんらかの別のプロジェクトで対応する可能性はありますが、「やった方がよい」ことは膨大にあるので、それらにすべて対応していくと、本来達成したい目的が遠のいていくかなと考えています🤔💭 (なので言い換えると、本来達成したいことが遠のいてでもやるべきことかどうか？が正しい問いかなと考えています)

まずは今やるべきことをサクッと達成して、次にやるべきことを達成して、次の次にやるべきことを... といったカタチで進められたらなと考えています😆

**Comment by yasulab** [comment]
コチラ #7 で実装できたので完了としますね ;)
お疲れ様でした! 😸♨️✨
