### ISSUE TITLE
ウィンドウの横幅が大きいとき、サムネイル画像を repeat させずに対処できるようにしたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#54]
![image](https://user-images.githubusercontent.com/155807/49373277-ccc17c00-f740-11e8-9cf0-4f6cdc5425bd.png)

cf. https://yasslab.jp/ja/posts/coderdojo-japan-2018

**Comment by showw** [comment]
CoderDojoで使っても良い写真ってどこかにまとめてありますか？
子どもの写真を使えればいいんですが、肖像権などの問題もあり、確認がとれているものを複数いただければ、その中からピックアップして画像を作ります。
@yasulab

**Comment by showw** [comment]
CoderDojo御茶ノ水で撮った写真を使ってレイアウトしてみました。本人の顔が特定しにくく、かつ楽しそうな雰囲気を出したいなーと思って作ってみました。現在、チャンピオンの渡辺さんに写真を使ってもいいかどうか確認中です。

## PCの時
![image](https://user-images.githubusercontent.com/5765654/51582401-37a45d80-1f0f-11e9-9b26-4754c263b18b.png)

## スマホの時
![image](https://user-images.githubusercontent.com/5765654/51582412-45f27980-1f0f-11e9-969d-726120f712a0.png)

**Comment by showw** [comment]
リピートさせないようにすると、ブラウザの横幅が広いときにバンっとイメージ画像が左右で切れてしまうので、できれば避けたいと考えています。
現状においてpost記事の場合には、幅1920ピクセルの無難な雲（青空）の画像がデフォルトで使われるようになっています。(img/bg-sky.jpg)

基本はこの雲の画像を表示。1920より大きなモニタで閲覧される機会は（少ないと思うのですが）画像リピートされる、で良いのではないでしょうか。

もし今回のCorderDojoページのように記事に見合ったイメージ画像が必要な時は、幅1920で作る（もしくはmgnに依頼する）という形にしたいです。
今のオープンソースカフェの写真は、画像の横幅が960のため、変な場所でリピートされる状態になっていますので、CoderDojoの画像については、プルリク作って送りますね。

**Comment by yasulab** [comment]
> 基本はこの雲の画像を表示。1920より大きなモニタで閲覧される機会は（少ないと思うのですが）画像リピートされる、で良いのではないでしょうか。

良いと思います! 🆒 d(￣ ￣)✨

> もし今回のCorderDojoページのように記事に見合ったイメージ画像が必要な時は、幅1920で作る（もしくはmgnに依頼する）という形にしたいです。
> 今のオープンソースカフェの写真は、画像の横幅が960のため、変な場所でリピートされる状態になっていますので、CoderDojoの画像については、プルリク作って送りますね。

了解です! 🙆‍♂️ 下記ファイルが投稿のテンプレートファイルなので、プルリクの中で上記の仕様をコメントとして追記しておくと良さそうです ;)

https://github.com/yasslab/yasslab.jp/blob/master/_posts/20xx-xx-xx-template.md
