### ISSUE TITLE
サービス紹介の背景色のズレを直したい

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#548]
特定の横幅だと背景色がズレるようなので、後で確認したい 👀💨✅

![表示がズレる？](https://user-images.githubusercontent.com/155807/123042886-70bfbf80-d432-11eb-99e6-44482d26e6bf.png)

**Comment by yuki384** [comment]
imgを使っているので、imgの幅のズレを修正すれば解決しそうですね。

**Comment by yasulab** [comment]
コチラ解決済みなので Close しますね! 🙏 ✨ 
<img width="851" alt="image" src="https://github.com/yasslab/yasslab.jp/assets/155807/1d048fc7-bfd1-4f50-b633-be839461ce1b">
