### ISSUE TITLE
リンク押下時に、ヘッダーでテキストが隠れてしまう問題を改善したい

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#56]
一時的に次の修正を入れてますが、できれば h2 タグに直接 id を入れてもいいような状態に持っていきたいですね 🤔💭 cc/ @yasslab/mgn 

Hotfix: Hidden h2 texts when clicking its ID
https://github.com/yasslab/yasslab.jp/commit/141d6e1587815cd76424a4317a19b38e934fa883

**Comment by yuki384** [comment]
https://github.com/yasslab/railsguides.jp_web/pull/1069 と同じ対応で解決できそうです。

**Comment by yuki384** [comment]
https://github.com/yasslab/yasslab.jp/pull/460 で対応したのでcloseします。

**Comment by yasulab** [comment]
こちら対応ありがとうございます！(＞人＜ )💖
