### ISSUE TITLE
開発支援サービスのページに Waiting List を実装したい

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#57]
cf. [開発支援サービス - YassLab Inc.](https://yasslab.jp/ja/agile)

cc/ @megane9988 @showw @ooyama91 

## ストーリー

- 開発支援サービスのリソースは限られているため、対応可能なときと、そうでないときがある
- 現在の仕様だと、たまたま対応可能なときに、たまたま問い合わせした会社にチャンスがある
- 対応可能でないときはメールの Waiting List に登録できるようにして、次に対応可能な期間が判明したときにメールにてお知らせしたい。これにより、それぞれのプレイヤーに次のメリットがある:
   - 依頼したい人: [開発支援ページ](https://yasslab.jp/ja/agile)を何度もチェックしたり、問い合わせする必要がなくなる
   - YassLab 社: 現在のクライアントとの契約が完了したとき、次のお願いしたいクライアントにスムーズにご案内することができる

## やりたいこと

- Waiting List フォームの設置・表示
- 次に対応可能な期間はいつなのかを表示する (カレンダー形式?)
   - cf. https://yasslab.jp/ja/calendar
- 購読者への配信メール内にて、いつでも Unsubscribe できるようにする

**Comment by megane9988** [comment]
参考
![image](https://user-images.githubusercontent.com/1205958/49565370-4e482280-f96a-11e8-9146-f89deaf26fbd.png)

**Comment by megane9988** [comment]
- 埋まってます `-` (ハイフン)
- ご相談お待ちしております `○` (マル）

**Comment by showw** [comment]
こんな感じにしますー
![image](https://user-images.githubusercontent.com/5765654/49920408-7b0db400-feed-11e8-8005-f6d90f7eff84.png)

**Comment by yasulab** [comment]
ありがとうございます！こちらでお願いします(＞人＜ )✨

**Comment by showw** [comment]
## PC版コーディング済み
![image](https://user-images.githubusercontent.com/5765654/49996560-af0ed500-ffd2-11e8-87af-1432f1ea537e.png)

## タブレット
![image](https://user-images.githubusercontent.com/5765654/49996609-cb127680-ffd2-11e8-81ee-44e2cc343ca7.png)

## スマホ
![image](https://user-images.githubusercontent.com/5765654/49996645-e67d8180-ffd2-11e8-8031-fdad90899544.png)

＊タブレットとスマホの時は、「ご相談お待ちしております」などの文言は表示しないようにする予定。

**Comment by yasulab** [comment]
次は購読フォームの設置。アカウントなどの作成、簡易フォームの設置などは @yasulab が行うので、Assignee を切り替えておきました 🔧 💨

**Comment by yasulab** [comment]
@showw メール購読フォーム実装しました! 後ほどデザインを改善していただけると嬉しいです (＞人＜ )✨
![image](https://user-images.githubusercontent.com/155807/50461074-ef9d2400-09be-11e9-9536-c57789e86151.png)

**Comment by yasulab** [comment]
@yasslab/mgn 文言とレイアウト改善しました! 😆 フィードバックありがとうございます (＞人＜ )✨
![image](https://user-images.githubusercontent.com/155807/50950289-e185f200-14ec-11e9-812b-4dc1d555ccd4.png)

開発支援サービスのビジネスを安定させていくため、ひとまずは10社の登録を目指して進めていきたいと考えています🤔💭

.oO(打ち合わせ中は思いつかなかったですが、開発支援サービスとは別の切り口からメール登録する流れがあっても良いかもしれないですね。例えば「Railsチュートリアル・Railsガイドの法人向けサービスのメールお知らせサービス」とか。開発支援に関するクライアントが増えると直接的で嬉しいですが、他にも「当初は依頼を検討していなかったけど、メールみて興味が湧きました」といった法人があっても良いと思うので。)

**Comment by yasulab** [comment]
<div>
<span><img src="https://avatars1.githubusercontent.com/u/155807?v=4" width="16" height="16" alt="" /></span>
<a href='https://github.com/yasulab'>yasulab</a>
pushed to
<a href='https://github.com/yasslab/yasslab.jp/tree/master'>master</a>
at
<a href='https://github.com/yasslab/yasslab.jp'>yasslab/yasslab.jp</a>
(<a href='https://github.com/yasslab/yasslab.jp/compare/942410a48d01...bd35873e093d'>compare</a>)
</div>
<ul>
<li>
<a href='https://github.com/yasslab/yasslab.jp/commit/bd35873e093d43b226c86810e9db6975042b439c'><tt>bd35873</tt></a>
Centering メールでお知らせ section in Agile

</li>
</ul>

**Comment by yasulab** [comment]
こちら機能としては実装できているので、閉じちゃいますね!
ご対応ありがとうございました!! (＞人＜ )✨
