### ISSUE TITLE
QiitaAPIの調査と「いいね」の数の集計を実装したい

### ISSUE THREAD

**Issue by AnaTofuZ** [yasslab/yasslab.jp#6]
# 背景
#4 
並列して2APIの調査を行っているので別issueを切りました

## 関連issue
#5 

# TODO
- [x] ruby側でAPIを叩けるかどうか調査
- [x] ~実際にrake task化する~ -> Jekyll Pluginとして実装
- [x] ~rake taskのテストコードを作成~　-> 分離してテストを作成
- [x] いいねの数が実際に動的に変わるかどうかの確認

**Comment by yasulab** [comment]
Qiita API に関するサンプルスクリプトとしては YassLab Organization 内にある `qiita-*` 系のリポジトリのコードが参考になるかも 🤔💭
https://github.com/search?q=org%3Ayasslab+qiita

あとは社内ドキュメントの方にも Qiita API に関する情報 (特に上記リポジトリを実装した背景など) がいくつかまとまっています。こちらももし必要であれば適宜参照してもらえれば 📑 👀 
https://yasslab.qiita.com/search?q=Qiita+API

**Comment by AnaTofuZ** [comment]
スクリプトを書いてみた

```ruby
#!/usr/bin/env ruby

require 'net/http'
require 'json'
require 'uri'

#'いいねの集計'
uri = URI("https://qiita.com/api/v2/teams")
http = Net::HTTP.new(uri.host,uri.port)
http.use_ssl = true

req  = Net::HTTP::Get.new(uri.request_uri)
#req["Authorization"] = ENV.fetch("QIITA_TOKEN")

res = http.request(req)
p res.body
```
返り値が`"{\"message\":\"Unauthorized\",\"type\":\"unauthorized\"}"` となり上手く取得できない…

**Comment by AnaTofuZ** [comment]
アクセストークンのフォーマットが
`Authorization: Bearer 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcd`
でないといけないらしい
cf. https://qiita.com/api/v2/docs#%E8%AA%8D%E8%A8%BC%E8%AA%8D%E5%8F%AF

そこで `req["Authorization"] = "Bearer #{ENV.fetch("QIITA_TOKEN")}"` と書き換えた所正常に動作した

**Comment by AnaTofuZ** [comment]
これでAPI叩くぞ!!と思っていたのですが，なんとチームAPIは自分自身が登録しているチーム情報しか取得出来なかった．yasslabに所属している人々を引っ張るには静的idを記述して持ってくるしか無さそう…?

**Comment by AnaTofuZ** [comment]
確認すると記事を取得するのも自分自身の認証キーが必要みたいでした
cf. https://qiita.com/api/v2/docs#%E6%8A%95%E7%A8%BF

ここから考えるに
## 1
まずyasslabメンバーにQiitaのアクセストークンを発行してもらう
## 2
それをなんらかの形で集約する
## 3
各ユーザーごとに集計をとり，それを加算する

という流れになりそうです

**Comment by AnaTofuZ** [comment]
```ruby
#!/usr/bin/env ruby

require 'net/http'
require 'json'
require 'uri'

#'いいねの集計'
uri = URI("https://qiita.com/api/v2/users/")
http = Net::HTTP.new(uri.host,uri.port)
http.use_ssl = true


member = %w(yasulab himajin315 hanachin_ hachi8833 aokabin nalabjp siman nanophate anatofuz)
p member
member.each do |m|
    uri = URI.join(uri,m)
    p uri
    req  = Net::HTTP::Get.new(uri.request_uri)
    req["Authorization"] = "Bearer #{ENV.fetch("QIITA_TOKEN")}"
    json = http.request(req)
    res = JSON.parse(json.body, {:symbolize_names => true})
    p res[:id]
end
```

URIの連結で `/` の有無が問題でしたが，正常にyasslabのユーザー情報を持ってくることが出来ました

**Comment by AnaTofuZ** [comment]
続いてはこちらを検証する
cf. https://qiita.com/api/v2/docs#get-apiv2usersuser_iditems

**Comment by AnaTofuZ** [comment]
各記事のidを取り出す事が出来た
https://github.com/yasslab/yasslab.jp/pull/8/commits/b96eb023678c0f4bad565a0bdb80002c126178a1
https://github.com/yasslab/yasslab.jp/pull/8

**Comment by AnaTofuZ** [comment]
いいねの数を集計することが出来ました．現在で716件でした
cf. https://github.com/yasslab/yasslab.jp/pull/8/commits/d4d22379e1eca5e47190af8e721122e8bdd2376e

**Comment by yasulab** [comment]
> いいねの数を集計することが出来ました．現在で716件でした

お...? ここで表示されている値と違うかも >< 💦 
https://qiita.com/organizations/yasslab

**Comment by AnaTofuZ** [comment]
投稿が87件になってたので，記事の取得の部分がおかしい事がわかりました．
メンバーは全員入れているので人数は揃っていると思います

**Comment by yasulab** [comment]
お、原因に目星が付いているようでよかったです! 👍 ✨

**Comment by AnaTofuZ** [comment]
取得に関して1ページの最大値がデフォルトでは20件だった為，一人あたりの記事数が正常に取れていなかった．
yasslabのメンバーは100件以下で今のところ投稿しているので, 
`users/#{m}/items",query:{"per_page"=>100}` とクエリパラメータに100件取得すように追記した

cf. https://qiita.com/api/v2/docs#get-apiv2authenticated_useritems

**Comment by AnaTofuZ** [comment]
検証した所6270いいねが取得できた．実際の値は6277なので，どこかで7が抜け落ちている…

**Comment by AnaTofuZ** [comment]
記事数は150件取得できていた(正常値)なので，いいねの加算の部分の処理が原因のよう

**Comment by AnaTofuZ** [comment]
試していたらAPI利用制限に引っ掛かった模様…

**Comment by AnaTofuZ** [comment]
どうもAPI経由では「いいね」は正常に入手できない模様
cf. https://qiita.com/yosukesuzuki/items/ddc7678722d1a1323df3

スクレイピングで行ってしまうのが早かったりしそうですね

**Comment by AnaTofuZ** [comment]
RubyからQiitaのいいねを取得することが出来たので，次はどうやって値を保存させるか考えてみます

**Comment by AnaTofuZ** [comment]
保存先としてはポスグレにscheme定義して流しこむという方法もありますが，ちょっと重いかなという印象です．Jekyll Pluginで良い感じに値を保存させることが出来ないか調べてみます

**Comment by AnaTofuZ** [comment]
調べた所Jekyll Pluginを使えばviewに値を渡せるので特別保存させなくても出来そうということがわかった

**Comment by AnaTofuZ** [comment]
https://github.com/yasslab/yasslab.jp/pull/8　で実装を行いましたがリアルタイムで更新が行われない問題が発生しました．
原因としては `initialize` メソッドはjekyllが初回デプロイ時に実行し，以降そのインスタンスが保存されるからであるようです．

対策としては
- `render` メソッド内でアクセスするように修正
- cron スケジューラーを設定
- ci側で制御

などを考えています．
ただ `render`でアクセスするのは毎アクセス時に要求をするのでコストとして大きいかな…という印象です

**Comment by yasulab** [comment]
集計自体は問題なくているので、Issue としては完了としますね ;)
集計および更新のタイミングについては下記の Issue を立てておきました! 📝 💨 
https://github.com/yasslab/yasslab.jp/issues/17

**Comment by yasulab** [comment]
> 集計自体は問題なくできている

補足です。本番環境でも動いていることが確認できたので「完了」といたしました!
実装お疲れ様でした〜 😸♨️✨
https://yasslab.jp/ja
