### ISSUE TITLE
note作成 登壇: Remote Work Tech Talk #1 @ 7/21

### ISSUE THREAD

**Issue by rakuda-san-desu** [yasslab/yasslab.jp#611]
https://yasslab.qiita.com/shared/items/ab25d3ff47cedf7746af
https://twitter.com/doyaaaaaken/status/1536888470802944001?s=21&t=qE8jPuBLaGWUXmjufSJTwg

ノート記事を準備する📖

**Comment by rakuda-san-desu** [comment]
草案: https://editor.note.com/notes/n08d2b784837c/edit/

**Comment by Yuppymam** [comment]
@rakuda-san-desu 
画像を使わせていただいているので、キャプションに画像の引用元など追記してみました🙏 その他は特に気になる点はありませんでした！最後のPR良いですね👍🥳 対応ありがとうございます✨

**Comment by rakuda-san-desu** [comment]
レビューと調整ありがとうございます🙏✨

**Comment by rakuda-san-desu** [comment]
カバー画像
https://www.figma.com/file/AeqyL9A03wAC02A5lL5vyb/note%E8%A8%98%E4%BA%8B%E3%82%AB%E3%83%90%E3%83%BC%E7%94%BB%E5%83%8F?node-id=2031%3A36
![Remote_Work_Tech_Talk_1](https://user-images.githubusercontent.com/41533420/173731267-5f4b5ce3-19e9-4885-ab77-07c8237c0ad0.png)

**Comment by rakuda-san-desu** [comment]
https://note.com/yasslab/n/n08d2b784837c

公開、周知を行ったのでクローズします😌✨
