### ISSUE TITLE
モバイル版だと少しだけ横にスクロールができてしまう

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#63]
iOS (Safari, Chrome) と Chrome Developer Tools で確認済み ✅ うーん、なんでだろう...? 🤔💭
複数のページで同じ現象が確認できたので、全体に関するCSSのどこかに 🐛 がありそう 👀 💦 
![image](https://user-images.githubusercontent.com/155807/50063153-629fe100-01ee-11e9-8066-8471ca2b17e2.png)

**Comment by megane9988** [comment]
mystyle.scss 
![image](https://user-images.githubusercontent.com/1205958/50127862-2b950280-02b6-11e9-9e9c-10c59d5ec3ad.png)


```
footer #contact-form {
    padding: 20px 15px;
}
```

**Comment by yasulab** [comment]
こちら僕の方で直しておきました! 🔧 ✅ ✨ 
ヒントありがとうございます! (＞人＜ )✨
