### ISSUE TITLE
ヘッダーのロゴ画像をクリックしたらブランドアセットページに誘導したい ↴

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#85]
Algolia のロゴを右クリックするとこういう表示が出てきたんだけど、まさにこの情報が欲しかったメッチャいいやん...という気持ちになっている 😳✨ (弊社のコーポレートサイトにも導入したい)

![image](https://user-images.githubusercontent.com/155807/54248476-26c3b000-4580-11e9-9400-3596897a0eca.png)

cf. https://www.algolia.com/
cf. https://yasslab.jp/ja/brand

**Comment by yuki384** [comment]
https://github.com/yasslab/yasslab.jp/pull/262 
実装してみました〜！( ｰ`ωｰ´)✨

こんな感じで、ロゴ画像を右クリックすると左上に表示されます。文言はもっといい感じにできそうです 🤔💭 
![image](https://user-images.githubusercontent.com/31533303/73608790-55b89980-460a-11ea-9329-abcd2836f67b.png)

**Comment by yasulab** [comment]
こちら対応されたので Close しますね！🛠💨✨
