### ISSUE TITLE
存在しない `site.*` 変数を呼び出したときにエラーを出したい

### ISSUE THREAD

**Issue by yasulab** [yasslab/yasslab.jp#86]
🤔.oO(よく使う用語+リンクはショートカットできるようにそれぞれ変数を用意したんだけど、Typo などで参照先がなかったらエラーが出る仕組みがあると良さそう)

![image](https://user-images.githubusercontent.com/155807/54328922-0dd7ff00-4653-11e9-90ef-c21515e1ff38.png)

**Comment by nanophate** [comment]
html-proofer  使っているなら、`check_external_hash` にあるような機能で確認できそうですね。

> Checks whether external hashes exist (even if the webpage exists). This slows the checker down.
> https://github.com/gjtorikian/html-proofer/blob/2e747cf84f820e98f9ca7041e3235a9b5c9d2bd4/README.md#configuration

**Comment by yasulab** [comment]
お、情報 Thx!! 😻 ただちょっと手元で試してみましたが、期待したような動きにはなってなさそうでした... 😹

![image](https://user-images.githubusercontent.com/155807/54333767-09b5dc80-4667-11e9-9b18-e10af62632a6.png)

cf. https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis

👀 💭 (有効にしたはずなのに check_external_hash が有効になってないようにも見える...? )

**Comment by yasulab** [comment]
こちら note への移行に伴って site 変数を参照する機会がほとんどなくなったので、一旦 Close しますね！🛠💨✨ https://yasslab.jp/ja/news
