### ISSUE TITLE
メンバーそれぞれの紹介文をください

### ISSUE THREAD

**Issue by showw** [yasslab/yasslab.jp#9]
顔写真の下に入れるテキストを30〜40文字程度で支給をお願いします。
以下の９人。

@hanachin
@himajin315
@nanophate
@siman
@anatofuz
@aokabin
@yasulab
@nalabjp
@hachi8833

**Comment by yasulab** [comment]
Issue 作成ありがとうございます 😸 書きました! ✅ https://yasslab.jp/ja
